#!/usr/bin/env bash
# discover-ssh-accounts.sh — Build the machine-local GitHub SSH account map.
#
# Scans ~/.ssh/config for Host entries pointing to github.com, probes each
# with `ssh -T` to discover the authenticated GitHub username, and writes
# the result to ~/.config/code-practices/accounts.yaml.
#
# Run once per machine after setting up SSH keys. Re-run after adding new keys.
#
# Usage:
#   bash .claude/scripts/discover-ssh-accounts.sh
#   bash .claude/scripts/discover-ssh-accounts.sh --dry-run   # print without writing
set -euo pipefail

SSH_CONFIG="${HOME}/.ssh/config"
OUTPUT_DIR="${HOME}/.config/code-practices"
OUTPUT_FILE="${OUTPUT_DIR}/accounts.yaml"
DRY_RUN=false
TMPDIR_LOCAL="${TMPDIR:-/tmp}"

if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
fi

if [[ ! -f "$SSH_CONFIG" ]]; then
    echo "[!!] ~/.ssh/config not found. Create it first." >&2
    exit 1
fi

echo "[--] Scanning ${SSH_CONFIG} for GitHub host aliases..."

# ---------------------------------------------------------------------------
# Parse ~/.ssh/config into a temp file: one line per alias
# Format: alias|identity_file
# Portable — no associative arrays (bash 3.2 compatible)
# ---------------------------------------------------------------------------

PARSED_TMP=$(mktemp "${TMPDIR_LOCAL}/ssh-accounts-parsed.XXXXXX")
RESULTS_TMP=""
trap 'rm -f "$PARSED_TMP" ${RESULTS_TMP:+"$RESULTS_TMP"}' EXIT

current_host=""
current_hostname=""
current_identity=""

_flush_block() {
    if [[ -n "$current_host" && "$current_hostname" == "github.com" && \
          -n "$current_identity" && "$current_host" != "*" ]]; then
        echo "${current_host}|${current_identity}" >> "$PARSED_TMP"
    fi
}

while IFS= read -r line || [[ -n "$line" ]]; do
    # Strip leading whitespace
    stripped="${line#"${line%%[! ]*}"}"

    case "$stripped" in
        [Hh]ost\ *)
            _flush_block
            current_host="${stripped#* }"
            current_hostname=""
            current_identity=""
            ;;
        [Hh]ost[Nn]ame\ *)
            current_hostname="${stripped#* }"
            ;;
        [Ii]dentity[Ff]ile\ *)
            current_identity="${stripped#* }"
            ;;
    esac
done < "$SSH_CONFIG"
_flush_block

if [[ ! -s "$PARSED_TMP" ]]; then
    echo "[!!] No GitHub host aliases found in ${SSH_CONFIG}." >&2
    echo "     Add Host entries with HostName github.com to ${SSH_CONFIG}." >&2
    exit 1
fi

alias_count=$(wc -l < "$PARSED_TMP" | tr -d ' ')
echo "[--] Found ${alias_count} GitHub host alias(es)"

# ---------------------------------------------------------------------------
# Probe each alias to discover the GitHub username
# Result file: one line per verified account
# Format: username|alias|identity_file
# ---------------------------------------------------------------------------

RESULTS_TMP=$(mktemp "${TMPDIR_LOCAL}/ssh-accounts-results.XXXXXX")

while IFS='|' read -r alias identity; do
    printf "[--] Probing %s ... " "$alias"

    output=$(ssh \
        -T \
        -o ConnectTimeout=5 \
        -o BatchMode=yes \
        -o StrictHostKeyChecking=accept-new \
        "$alias" </dev/null 2>&1 || true)

    # GitHub responds: "Hi <username>! You've successfully authenticated..."
    username=$(echo "$output" | sed -n 's/^Hi \([a-zA-Z0-9_-]*\)!.*/\1/p' | head -1)

    if [[ -n "$username" ]]; then
        echo "authenticated as ${username}"
        echo "${username}|${alias}|${identity}" >> "$RESULTS_TMP"
    else
        echo "failed (skipping)"
        echo "     Response: ${output}" >&2
    fi
done < "$PARSED_TMP"

if [[ ! -s "$RESULTS_TMP" ]]; then
    echo "[!!] No accounts could be verified. Check that SSH keys are accessible." >&2
    exit 1
fi

result_count=$(wc -l < "$RESULTS_TMP" | tr -d ' ')

# ---------------------------------------------------------------------------
# Build YAML content
# ---------------------------------------------------------------------------

yaml_header="# Auto-generated by: bash .claude/scripts/discover-ssh-accounts.sh
# Regenerate after adding new SSH keys or GitHub accounts.
# Maps GitHub username -> SSH host alias + identity file.
accounts:"

yaml_entries=""
while IFS='|' read -r username alias identity; do
    yaml_entries="${yaml_entries}
  ${username}:
    ssh_host: ${alias}
    identity_file: ${identity}"
done < "$RESULTS_TMP"

yaml_content="${yaml_header}${yaml_entries}"

# ---------------------------------------------------------------------------
# Write or print
# ---------------------------------------------------------------------------

if [[ "$DRY_RUN" == "true" ]]; then
    echo ""
    echo "=== Would write to ${OUTPUT_FILE} ==="
    echo "$yaml_content"
    exit 0
fi

mkdir -p "$OUTPUT_DIR"
printf '%s\n' "$yaml_content" > "$OUTPUT_FILE"
chmod 600 "$OUTPUT_FILE"

echo ""
echo "[ok] Written: ${OUTPUT_FILE}"
echo "[ok] ${result_count} account(s) mapped."
