export const IPC = {
  GET_REGISTRY: "get-registry",
  OPEN_WORKFLOW: "open-workflow",
  REGISTRY_UPDATED: "registry-updated",
  PICK_FOLDER: "pick-folder",
  RUN_WORKFLOW: "run-workflow",
  REVEAL_PATH: "reveal-path",
  SCHEDULE_STATUS: "schedule-status",
  SCHEDULE_ENABLE: "schedule-enable",
  SCHEDULE_DISABLE: "schedule-disable",
  READ_LOG: "read-log",
  LIST_BRANCHES: "list-branches",
  SCAFFOLD_WORKFLOW: "scaffold-workflow",
  WRITE_ACTIVITY_LOG: "write-activity-log",
  TRANSCRIBE_AUDIO: "transcribe-audio",
  COPY_TO_CLIPBOARD: "copy-to-clipboard",
  GET_TRANSCRIPTION_LOG: "get-transcription-log",
  SAVE_TRANSCRIPTION: "save-transcription",
  READING_LIST_IMPORT: "reading-list-import",
  READING_LIST_ADD_URL: "reading-list-add-url",
  READING_LIST_GET_ENTRIES: "reading-list-get-entries",
} as const;
